spring:
  application:
    name: cloud-provider-user
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learninglibrary?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password:
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  consumer:
    check: false
  scan:
    base-packages: cn.vesns.provider.user.impl
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://127.0.0.1:8848
  # 负载均衡
  provider:
    loadbalance: roundrobin
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.vesns.provider.user.pojo.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
